# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Stew < Formula
  desc "A powerful CLI for the Create and Deploy App project"
  homepage ""
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/The-Grand-Stew/stew/releases/download/0.1.0/stew_0.1.0_macOS_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1c7c3bda31d759f6b426a14e39945b3ab1c2318b3347ee216327df3c99e20df7"

      def install
        bin.install "stew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/The-Grand-Stew/stew/releases/download/0.1.0/stew_0.1.0_macOS_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "391fe921763b37345f11f9efb05b4df8db2ba7cf49a69902c46911a8b918d361"

      def install
        bin.install "stew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/The-Grand-Stew/stew/releases/download/0.1.0/stew_0.1.0_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bb795baddce76480594f36dc426dde5c9bccf49a8368e121e0afb4130cab0f63"

      def install
        bin.install "stew"
      end
    end
  end

  depends_on "terraform"
  depends_on "git"
  depends_on "go"
  depends_on "terragrunt"
end
