# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "private"
class Stew < Formula
  desc "A powerful CLI for the Create and Deploy App project"
  homepage ""
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/veda-p/stew/releases/download/v0.0.3/stew_0.0.3_macOS_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "abb9e075aa1a24a2fee49955a46e9b3ce31952853644d8fdf8eb178f4dcc5aa9"

      def install
        bin.install "stew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/veda-p/stew/releases/download/v0.0.3/stew_0.0.3_macOS_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4451a41e1718b4f2fc2fe830cef99d86d790157b6c05e565dc575d3797a53338"

      def install
        bin.install "stew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/veda-p/stew/releases/download/v0.0.3/stew_0.0.3_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2b5eafda3f351c84e16f90bf43e1281a036816104cd2a7eda46b21876b56d240"

      def install
        bin.install "stew"
      end
    end
  end

  depends_on "terraform"
  depends_on "git"
  depends_on "go"
end
