# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private"
class Stew < Formula
  desc "A powerful CLI for the Create and Deploy App project"
  homepage ""
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/The-Grand-Stew/stew/releases/download/0.1.0/stew_0.1.0_macOS_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "0f09a21f3e4eda09651b32a25eb7cd9e2a34a9f3cc6906576d368dfbf1bb2f3f"

      def install
        bin.install "stew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/The-Grand-Stew/stew/releases/download/0.1.0/stew_0.1.0_macOS_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ad16b090846cfa4e8e6bfe1057a5c4c5b07a884ca458fb8c36bb4e94aa378914"

      def install
        bin.install "stew"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/The-Grand-Stew/stew/releases/download/0.1.0/stew_0.1.0_Linux_x86_64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6e580811f1de49a673bb0f1f40afbd94a40ccae244cb2ba262653e17c832e71f"

      def install
        bin.install "stew"
      end
    end
  end

  depends_on "terraform"
  depends_on "git"
  depends_on "go"
  depends_on "terragrunt"
end
